### 1要素の値の取り出し(ndarray)
・各軸の番号を順に指定することで、要素の一つの値を取り出せる

In [2]:
import pandas as pd
import numpy as np

In [3]:
a1 = np.array([0,1,2])
print(a1)
print(a1[0])

[0 1 2]
0


In [4]:
a2 = np.array([[0,1,2],[3,4,5]])
print(a2)
print(a2[0,1])

[[0 1 2]
 [3 4 5]]
1


In [5]:
a3 = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(a3)
print(a3[1,0,2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
8


### 1要素の値の変更(ndarray)
・取り出す代わりに値を代入すると、ndarrayの要素の一つの値を変更できる

In [6]:
a1[0] = 99
print(a1)

[99  1  2]


In [7]:
a2[0,1] = 99
print(a2)

[[ 0 99  2]
 [ 3  4  5]]


In [8]:
a3[1,0,2] =99
print(a3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7 99]
  [ 9 10 11]]]


### 1要素の値の取り出し(DataFrame)
・DataFrameに対しては、**at**を使って行番号(行ラベル)と列ラベルを指定することで、要素の1つの値を取り出せることができる<br>
・**iat**を使うと、行、列ともにラベルではなく番号で1つの要素を指定できる

In [9]:
df = pd.read_csv("../02/wholesale_customers.csv",sep=",",skiprows=13,header=0)
print(df.shape)
print(df.info())
display(df.head())
df6 = df.iloc[1:4,3:6]
display(df6)
print(df6.at[2,"Frozen"])

(440, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Channel           440 non-null    int64 
 1   Region            440 non-null    object
 2   Fresh             440 non-null    int64 
 3   Milk              440 non-null    int64 
 4   Grocery           440 non-null    int64 
 5   Frozen            440 non-null    int64 
 6   Detergents_Paper  440 non-null    int64 
 7   Delicatessen      440 non-null    int64 
dtypes: int64(7), object(1)
memory usage: 27.6+ KB
None


Channel Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  \
0        2  Other  12669  9656     7561     214              2674   
1        2  Other   7057  9810     9568    1762              3293   
2        2  Other   6353  8808     7684    2405              3516   
3        1  Other  13265  1196     4221    6404               507   
4        2  Other  22615  5410     7198    3915              1777   

   Delicatessen  
0          1338  
1          1776  
2          7844  
3          1788  
4          5185

Milk  Grocery  Frozen
1  9810     9568    1762
2  8808     7684    2405
3  1196     4221    6404

2405


In [12]:
### iatは0から始まる行番号で行を指定することになる
print(df6.iat[2,1])

4221


### 1要素の値の変更(DataFrame)
・DataFrameでもndarrayと同様に、値の代入によって要素の1つの値を変更することができる

In [14]:
df6.at[2,"Frozen"] =99
display(df6)

Milk  Grocery  Frozen
1  9810     9568    1762
2  8808     7684      99
3  1196     4221    6404

In [15]:
df6.iat[2,1] = 88
display(df6)

Milk  Grocery  Frozen
1  9810     9568    1762
2  8808     7684      99
3  1196       88    6404