In [1]:
import pandas as pd
import numpy as np

In [2]:
a1 = np.array([[11,3,3],[6,18,17]])
a1

array([[11,  3,  3],
       [ 6, 18, 17]])

In [3]:
a2 = np.array([[18,1,8],[4,5,3]])
a2

array([[18,  1,  8],
       [ 4,  5,  3]])

In [4]:
a3 = np.array([[8,18],[5,5],[11,6]])
a3

array([[ 8, 18],
       [ 5,  5],
       [11,  6]])

In [5]:
a4 = np.array([1, 4, 2, 17, 7])
a4

array([ 1,  4,  2, 17,  7])

In [6]:
print(a3.ndim)
print(a3.shape)

2
(3, 2)


In [7]:
print(a4.ndim)
print(a4.shape)

1
(5,)


In [8]:
a5 = a1 + a2
a5

array([[29,  4, 11],
       [10, 23, 20]])

In [9]:
a6 = a5 **2
a6

array([[841,  16, 121],
       [100, 529, 400]])