In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim ##次元数

1

In [ ]:
arr.shape ##各次元の要素の数

(5,)

In [8]:
arr[0] ##pythonのリストと同じようにアクセスできる

1

In [9]:
arr[1:4] ##スライスもできる

array([2, 3, 4])

## 条件付き抽出

In [10]:
arr11 = np.array([1, 2, 3, 4, 5, 6])

In [11]:
arr11 < 3

array([ True,  True, False, False, False, False])

In [12]:
arr11[arr11 < 3] ##条件を満たす要素のみ取り出す

array([1, 2])