In [18]:
import numpy as np

In [19]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [20]:
type(arr)

numpy.ndarray

In [21]:
arr.ndim ##次元数

1

In [22]:
arr.shape ##各次元の要素の数

(5,)

In [23]:
arr[0] ##pythonのリストと同じようにアクセスできる

1

In [24]:
arr[1:4] ##スライスもできる

array([2, 3, 4])

In [25]:
arr2 = np.array([[3,4,5],[6,7,8]])
print(arr2)

[[3 4 5]
 [6 7 8]]


In [26]:
print(arr2[0,2]) #0番目の行2番目の要素

5


In [31]:
arr2[1,1] = 99 # 1番目の行1番目の要素を99に変更
print(arr2)

[[ 3  4  5]
 [ 6 99  8]]


## 条件付き抽出

In [28]:
arr11 = np.array([1, 2, 3, 4, 5, 6])

In [29]:
arr11 < 3

array([ True,  True, False, False, False, False])

In [30]:
arr11[arr11 < 3] ##条件を満たす要素のみ取り出す

array([1, 2])