In [1]:
import numpy as np

In [2]:
arr3 = np.array([1, 2, 3, 4, 5, 6])
print(arr3)

[1 2 3 4 5 6]


In [3]:
arr3.reshape(2, 3) ##reshapeで行列に変換できる

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr4 = np.array([1, 2, 3])
arr5 = np.array([4, 5, 6])

In [5]:
arr6 = np.concatenate([arr4, arr5]) ##concatenateで結合できる
arr6

array([1, 2, 3, 4, 5, 6])

In [6]:
arr7, arr8 = np.split(arr6, [3]) ##splitで分割できる

In [7]:
arr7

array([1, 2, 3])

In [8]:
arr8

array([4, 5, 6])