In [1]:
import numpy as np

In [2]:
a = np.array([1,3,5])
b = np.array([5,7,9])

In [3]:
a

array([1, 3, 5])

In [4]:
b

array([5, 7, 9])

In [5]:
type(a)

numpy.ndarray

In [6]:
a+b

array([ 6, 10, 14])

In [7]:
a*b

array([ 5, 21, 45])

In [8]:
a.ndim

1