In [2]:
import numpy as np

In [3]:
a1 = np.array([5, 9, 1])
a1

array([5, 9, 1])

In [4]:
a2 = np.array([[1, 2, 3],[4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [9]:
a1+10

array([15, 19, 11])

In [10]:
a1-1

array([4, 8, 0])

In [11]:
1/a1

array([0.2       , 0.11111111, 1.        ])

In [12]:
a1*a1

array([25, 81,  1])

In [13]:
a1**3

array([125, 729,   1], dtype=int32)