In [2]:
import numpy as np

In [3]:
a1 = np.array([5, 9, 1])
a1

array([5, 9, 1])

In [4]:
a2 = np.array([[1, 2, 3],[4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
a1+10

array([15, 19, 11])

In [8]:
a1-1

array([4, 8, 0])

In [9]:
1/a1

array([0.2       , 0.11111111, 1.        ])

In [10]:
a1*a1

array([25, 81,  1])

In [11]:
a1**3

array([125, 729,   1], dtype=int32)

In [13]:
a1 = np.array([[0],[1],[2]]) 
b1 = np.array([1,2,3])   
print(a1 + b1)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [14]:
a2 = np.array([[0,1],[2,3],[4,5]]) 
b2 = np.array([[1,2,3],[4,5,6]])  
print(a2 + b2)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [15]:
a3 = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]]) 
b3 = np.array([[1],[4]])  
print(a3 + b3)

[[[ 2  3  4]
  [ 8  9 10]]

 [[ 8  9 10]
  [14 15 16]]]
